apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.service.type: LoadBalancer
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: web-tcp
  name: web-tcp
  namespace: default
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  selector:
    io.kompose.service: web
  type: LoadBalancer
status:
  loadBalancer: {}
