apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.service.type: LoadBalancer
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v
        kompose.service.type: LoadBalancer
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/apartment-scraper-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - args:
            - uvicorn
            - apartment_scraper.api:app
            - --host
            - 0.0.0.0
            - --port
            - "80"
          env:
            - name: DATABASE
              value: apartments
            - name: HOST
              value: database
            - name: PASSWORD
              value: postgres
            - name: USERNAME
              value: postgres
          image: golgor/apartment-scraper-web:0.0.1
          name: web
          ports:
            - containerPort: 80
              hostPort: 8000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
